### ISSUE TITLE
怎么样才能宽高自适应呢

### ISSUE THREAD

**Issue by qingweiSun** [pujiaxin33/StackUI#1]
![image](https://user-images.githubusercontent.com/16513906/144534526-667467d2-8cd0-4cf6-91d0-f83f58b3c945.png)

 let stack = VStack {
      Label("昵称").font(.systemFont(ofSize: 18, weight: .medium))
      Label("昵称").font(.systemFont(ofSize: 18, weight: .medium))
      Label("昵称").font(.systemFont(ofSize: 18, weight: .medium))
      Label("昵称").font(.systemFont(ofSize: 18, weight: .medium))
      Label("昵称").font(.systemFont(ofSize: 18, weight: .medium))
      Label("昵称").font(.systemFont(ofSize: 18, weight: .medium))
      Label("昵称").font(.systemFont(ofSize: 18, weight: .medium))
      Label("昵称").font(.systemFont(ofSize: 18, weight: .medium))
      Label("昵称").font(.systemFont(ofSize: 18, weight: .medium))
      Label("昵称").font(.systemFont(ofSize: 18, weight: .medium))
      Label("昵称").font(.systemFont(ofSize: 18, weight: .medium))
      Label("昵称").font(.systemFont(ofSize: 18, weight: .medium))
      Label("昵称").font(.systemFont(ofSize: 18, weight: .medium))
      Label("昵称").font(.systemFont(ofSize: 18, weight: .medium))
      Label("昵称").font(.systemFont(ofSize: 18, weight: .medium)).backgroundColor(UIColor.red)
      
      TextButton().apply { button in
        button.text = "xxxxxxx"
        button.contentMode = .center
      }
      Button().title(nickName.asDriver(onErrorJustReturn: nil), for: .normal)
    }

宽度被撑满了

**Comment by pujiaxin33** [comment]
因为VStack初始化方法里面，alignment默认值为.fill，你修改为VStack(alignment: .leading)即可。
