### ISSUE TITLE
您好，ZStack 如何实现？

### ISSUE THREAD

**Issue by eric1202** [pujiaxin33/StackUI#4]
首先感谢大佬的开源代码

请问下HStack 和 VStack 已经有了，那么怎么实现垂直ZStack的功能呢？

**Comment by zyflovelam** [comment]
好问题，同问，我看大佬有一段时间没更新了，有想法吗？我个人想法，HStack和VStack是基于UIStackView，但是ZStack不行，ZStack应该是遍历，按照初始方法里的参数，所有的subviews挨个加到当前view上，当前view作为容器，然后按照subviews里配置的参数，比如位置，比如frame信息等，来进行排版，可以自己尝试一下先

**Comment by pujiaxin33** [comment]
> 好问题，同问，我看大佬有一段时间没更新了，有想法吗？我个人想法，HStack和VStack是基于UIStackView，但是ZStack不行，ZStack应该是遍历，按照初始方法里的参数，所有的subviews挨个加到当前view上，当前view作为容器，然后按照subviews里配置的参数，比如位置，比如frame信息等，来进行排版，可以自己尝试一下先

感谢你的答复，确实如此，基于UIStackView，不能实现ZStack的效果。

**Comment by pujiaxin33** [comment]
0.0.15版本已经支持ZStack了。
