### ISSUE TITLE
怎么支持第三方SDK里面的View呢？ 比如第三方轮播图SDCycleScrollView等

### ISSUE THREAD

**Issue by xiaoyao20084321** [pujiaxin33/StackUI#5]
怎么支持第三方SDK里面的View呢？ 比如第三方轮播图SDCycleScrollView等。
去继承这个第三方view， 然后写一个apply方法， 将原来的对象暴露出来？然后在apply闭包里设置这个第三方view的属性嘛，但是如果这样做的话， 就不支持publisher了吧。

**Comment by pujiaxin33** [comment]
可以参考这里的描述: https://github.com/pujiaxin33/StackUI#the-parent-class-cannot-be-modified-conform-the-protocol
然后自己搞一个继承SDCycleScrollView的子视图，并且遵从StackUIView，然后再添加自己想要扩展的方法。
