### ISSUE TITLE
使用if语句，更新的时候必须得重新删除重新添加嘛？

### ISSUE THREAD

**Issue by xiaoyao20084321** [pujiaxin33/StackUI#6]
使用if语句，更新的时候必须得重新删除重新addSubview嘛？如果是在cell里面做更新的话， 频繁的删除添加会不会对性能不好

**Comment by pujiaxin33** [comment]
是的，if语句更新的话，需要重新创建视图。所以，不适合在cell里面使用if语句，尽可能的使用静态视图。
